### ISSUE TITLE
Not working locally

### ISSUE THREAD

**Issue by jaumeavila** [GeneaLabs/laravel-appleseed#3]
I have an alias to a project of mine called eventos.dev and when I go to the main route, it is detected as a favicon route.
I have checked the code, and according to it, there are 2 matches and that is why the 404 is shown.

**Comment by mikebronner** [comment]
What do you mean by `alias`? Also, what is the the full route of your main route? That will help me look into this. Thanks!

**Comment by jaumeavila** [comment]
By alias I mean a host alias. "eventos.dev" points to the / route in my project.
I printed the file variable you have and it echoed "eventos.dev".
Can't tell you much more because I have removed the package, sorry,

**Comment by mikebronner** [comment]
This should now be fixed in release 0.2.1. Thank you @jaumeavila for reporting this! (I hadn't implemented the plugin myself yet, which I should have.) I added additional unit test to test for a valid base route, and well as a the favicon specific routes.
